name: Deploy Project
on: [push, workflow_dispatch] #we run this event whenever we push something to the remote repository
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci #we can also use: npm install
      - name: run tests
        run: npm test
  deploy: 
    needs: test-project
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci #we can also use: npm install
      - name: Build Project
        run: npm run build
      - name: deploy
        run: echo "deploying..."