name: Output Information
on: issues
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: output github context #it may be an object or a collection of data
        run: echo "${{ toJSON(github.event) }}"